In [159]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import sympy as smp
from ipywidgets import interact

#### 1) How many multiplications and additions do you need to perform a matrix multiplication between a (n, k) and (k, m) matrix? Explain.

$$
nmk
$$

##### Explanation: 

The output of the matrix multiplication will be a matrix of shape (n, m) .
For example :

In [119]:
m, n, k = 4, 5, 3
M1 = np.random.randint(-9,10,(n,k))
M2 = np.random.randint(-9,10,(k,m))
print("M1 :\n",M1)
print("shape :",M1.shape)
print('\n')
print("M2 :\n",M1)
print("shape :",M2.shape)

M1 :
 [[ 1  4  5]
 [ 3 -9 -9]
 [-5  6  9]
 [-2  8  5]
 [ 9  7 -4]]
shape : (5, 3)


M2 :
 [[ 1  4  5]
 [ 3 -9 -9]
 [-5  6  9]
 [-2  8  5]
 [ 9  7 -4]]
shape : (3, 4)


In [120]:
out = np.matmul(M1,M2)
print("M1 @ M2 :\n",out )
print("shape :",out.shape)

M1 @ M2 :
 [[-39  11 -14  16]
 [ 30   6  51 -48]
 [-17 -43 -58  56]
 [-11  15 -33  28]
 [-37 141  50 -52]]
shape : (5, 4)


#### 2) Write Python code to multiply the above two matrices. Solve using list of lists and then use numpy. Compare the timing of both solutions. Which one is faster? Why?

##### A function 'matrix_multiply' to multiply matrices as lists

In [121]:
def matrix_multiply(M1 : list,M2 : list):
    out = []
    n = len(M1)
    k = len(M1[0])
    if len(M2) != k:
        print("shape mismatch")
        return False
    m = len(M2[0])
    for i in range(n):
        row = [0]*m
        for j in range(m):
            for K in range(k):
                row[j] += M1[i][K] * M2[K][j]
        out.append(row)
    return out

M1L = list(M1)
M2L = list(M2)
print("M1 @ M2 (self made function):")
for row in matrix_multiply(M1L,M2L):
    row = [str(x) for x in row]
    print("\t".join(row))
print("\nM1 @ M2 (numpy):\n",np.matmul(M1,M2))

M1 @ M2 (self made function):
-39	11	-14	16
30	6	51	-48
-17	-43	-58	56
-11	15	-33	28
-37	141	50	-52

M1 @ M2 (numpy):
 [[-39  11 -14  16]
 [ 30   6  51 -48]
 [-17 -43 -58  56]
 [-11  15 -33  28]
 [-37 141  50 -52]]


##### Time comparision

matrix_multiply (self-made)

In [122]:
%%timeit
matrix_multiply(M1L,M2L)

50 µs ± 14.4 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


numpy.matmul

In [123]:
%%timeit
np.matmul(M1,M2)

2.68 µs ± 155 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


Conclusion : 
Numpy is faster. This is because firstly, it is written in C/C++, which is a faster language than python. (The same for-loop in C runs quicker than in python)

#### 3) Finding the highest element in a list requires one pass of the array. Finding the second highest element requires 2 passes of the the array. Using this method, what is the time complexity of finding the median of the array? Can you suggest a better method? Can you implement both these methods in Python and compare against numpy.median routine in terms of time?

##### For an array of size n, this method will have the worst case time complexity of $$ O(n^2) $$

In [124]:
def bubble_median(L : list):
    """
    L : list to find median in.
    """
    L = L.copy() # this line runs in O(n)
    l = len(L) # this line runs in O(n)
    for i in range(l//2 +1):
        for j in range(l-1,i,-1):
            if L[j] < L[i]:
                L[i],L[j] = L[j],L[i]
    if l%2 == 0:
        return (L[l//2] + L[l//2 -1])/2
    return L[l//2]
L = list(np.random.randint(-9,10,10))
print(" array :\t",L)
L_s = sorted(L)
print(" sorted array :\t",L_s)
print(" median (bubble):\t",bubble_median(L))
print(" median (numpy) :\t",np.median(L))


 array :	 [8, -3, -6, 0, 0, -5, -4, -8, -2, 9]
 sorted array :	 [-8, -6, -5, -4, -3, -2, 0, 0, 8, 9]
 median (bubble):	 -2.5
 median (numpy) :	 -2.5


##### A better method is to first sort the whole array using heap sort or merge sort, which will have worst case time complexity of $$ O(n \log n) $$ Then, we can find the median easily.

In [125]:
#Implementing Heap sort

def push_down(L,i,n):
    m = i
    if 2*i+1<n and L[2*i+1]<L[m]:
        m = 2*i+1
    if 2*i+2<n and L[2*i+2]<L[m]:
        m = 2*i+2
    if m==i:
        return
    L[i],L[m] = L[m],L[i]
    push_down(L,m,n)

def heapify(L,i,n):
    if 2*i+1 < n:
        heapify(L,2*i+1,n)
    if 2*i+2 < n:
        heapify(L,2*i+2,n)
    push_down(L,i,n)
def heap_sort(L):
    n = len(L)
    heapify(L,0,n)
    while n > 1:
        L[0],L[n-1] = L[n-1],L[0]
        n -= 1
        push_down(L,0,n)
    pass

L = list(np.random.randint(-9,10,11))
print("before head sort :\t",L)
heap_sort(L)
print("after heap sort :\t",L)

before head sort :	 [6, 6, -4, 8, -4, 8, 4, -8, -5, 9, -9]
after heap sort :	 [9, 8, 8, 6, 6, 4, -4, -4, -5, -8, -9]


In [126]:
def heap_median(L):
    L = L.copy()
    l = len(L)
    heap_sort(L)
    if l%2 == 0:
        return (L[l//2] + L[l//2 -1])/2
    return L[l//2]

In [127]:
L = list(np.random.randint(-9,10,10))
print(" array :\t",L)
print(" median (heap_sort):\t",heap_median(L))
print(" median (numpy) :\t",np.median(L))

 array :	 [-8, 3, -3, -7, -3, 2, 4, 6, -5, 8]
 median (heap_sort):	 -0.5
 median (numpy) :	 -0.5


In [128]:
Larray = np.random.randint(-9,10,1000) 
# It's necessary to have a large array size for heap_median to do better. 
# Try with size 10 and bubble_median would do better
L = list(Larray)

##### Time comparision

O(n^2) method

In [129]:
%%timeit
bubble_median(L)

51.1 ms ± 9.18 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


O(n*log(n)) method

In [130]:
%%timeit
heap_median(L)

9.54 ms ± 875 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


numpy.median

In [131]:
%%timeit
np.median(Larray)

48.8 µs ± 10.3 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


#### 4) What is the gradient of the following function with respect to x and y ? $$ x^2y + y^3\sin(x) $$

##### Answer

$$
\begin{bmatrix} 
2xy + y^3\cos(x) \\
x^2 + 3y^2\sin(x)
\end{bmatrix}
$$

##### Explanation

For $$ f(x,y) = x^2y + y^3\sin(x) $$ , we have 
$$
\frac{\partial f}{\partial x} = 2xy + y^3\cos(x) \\ 
\frac{\partial f}{\partial y} = x^2 + 3y^2\sin(x)
$$ as the partial derivatives of f wrt x and y respectively. 
Thus the gradient is given by
$$ 
\nabla f = 
\begin{bmatrix} 
{\frac{\partial f}{\partial x}} \\
{\frac{\partial f}{\partial y}}
\end{bmatrix} = 
\begin{bmatrix} 
2xy + y^3\cos(x) \\
x^2 + 3y^2\sin(x)
\end{bmatrix}
$$

#### 5) Use JAX to confirm the gradient evaluated by your method matches the analytical solution corresponding to a few random values of x and y

jax couldn't be imported correctly on my device, so I'm just going to find the gradiet numericaly myself. 

In [132]:
def f(x,y):
    return x**2 *y + y**3 * np.sin(x)

In [144]:
def nabla_f(x,y):
    dfdx = 2*x*y + (y**3)*np.cos(x)
    dfdy = x**2 + 3*(y**2)*np.sin(x)
    return np.array([dfdx,dfdy])
def nabla_f_numerical(x,y):
    dy = dx = 10**-10
    dfdx = (f(x+dx,y)-f(x,y))/dx
    dfdy = (f(x,y+dy)-f(x,y))/dy
    return np.array([dfdx,dfdy])

In [145]:
data = np.random.random((10,2))
nf = []
nfjx = []
er = []
for i in range(data.shape[0]):
    nf.append(nabla_f(*data[i]))
    nfjx.append(nabla_f_numerical(*data[i]))
    er.append(np.linalg.norm(nf[i]-nfjx[i]))
data = {
    "x":data[:,0],
    "y":data[:,1],
    "nabla_f (analytical)":nf,
    "nabla_f (numerical)":nfjx,
    "error":er
}
df = pd.DataFrame(data)
df

x         y                        nabla_f (analytical)  \
0  0.603207  0.081237   [0.0984472384121951, 0.37509013242582806]   
1  0.953510  0.463186     [0.9408241435239711, 1.434025767813076]   
2  0.279141  0.103584  [0.05889757455545343, 0.08678887574654802]   
3  0.929649  0.436653    [0.8616643838989398, 1.3226526762029076]   
4  0.371364  0.700691    [0.8409896755621887, 0.6724093557722642]   
5  0.916689  0.177631    [0.3290749564880871, 0.9154382883079689]   
6  0.000931  0.982969  [0.9516015957998011, 0.002699502901244806]   
7  0.699205  0.869528    [1.7191232175974895, 1.9487440508617968]   
8  0.306979  0.896181    [1.2363300984261871, 0.8223169633624785]   
9  0.277963  0.734110    [0.7885501028669217, 0.5208956366427778]   

                           nabla_f (numerical)         error  
0   [0.09844729198515978, 0.37509013256498136]  5.357315e-08  
1     [0.9408240853048255, 1.4340251208722066]  6.495552e-07  
2   [0.05889757431765119, 0.08678887469804053]  1.075136e-09  
3      [0.8616640734260272, 1.322653098156934]  5.238689e-07  
4     [0.8409900553729699, 0.6724093504217876]  3.798485e-07  
5     [0.3290751005025072, 0.9154385582910152]  3.059918e-07  
6  [0.9516015970004177, 0.0026995018633652057]  1.587033e-09  
7      [1.719123732257799, 1.9487444991028724]  6.824920e-07  
8     [1.2363304824347665, 0.8223177694333117]  8.928677e-07  
9     [0.7885503361393376, 0.5208958264724117]  3.007512e-07

#### 6) Use sympy to confirm that you obtain the same gradient analytically.

In [152]:
x,y = smp.symbols('x, y')
f = x**2 * y + y**3 * smp.sin(x)
f_as_mat = smp.Matrix([f])
f_free_var_mat = smp.Matrix(list(f.free_symbols))
f_grad = smp.transpose(f_as_mat.jacobian(f_free_var_mat))
f_grad

Matrix([
[ 2*x*y + y**3*cos(x)],
[x**2 + 3*y**2*sin(x)]])

#### 7) Create a Python nested dictionary to represent hierarchical information. We want to store record of students and their marks. Something like:

1. 2022
   1. Branch 1
      1. Roll Number: 1, Name: N, Marks:
         1. Maths: 100, English: 70 …
   2. Branch 2
2. 2023
   1. Branch 1
   2. Branch 2
3. 2024
   1. Branch 1
   2. Branch 2
4. 2025
   1. Branch 1
   2. Branch 2

In [153]:
D = {
    2022:{
        "Branch 1":{
            1: {"Roll number":1,
                "Name":"N",
                "Marks":{
                    "Maths":100,
                    "English":70,
                }}
        },
        "Branch 2":{
        },
    },
    2023:{
        "Branch 1":{
        },
        "Branch 2":{
        },
    },
    2024:{
        "Branch 1":{
        },
        "Branch 2":{
        },
    },
    2025:{
        "Branch 1":{
        },
        "Branch 2":{
        },
    },
}
year2022 = D[2022]
year2022Branch1 = year2022["Branch 1"]
year2022Branch1Student1 = year2022Branch1[1]
print(year2022Branch1Student1) # prints details of student

{'Roll number': 1, 'Name': 'N', 'Marks': {'Maths': 100, 'English': 70}}


#### 8) Store the same information using Python classes. We have an overall database which is a list of year objects. Each year contains a list of branches. Each branch contains a list of students. Each student has some properties like name, roll number and has marks in some subjects.

In [156]:
class Student:
    def __init__(self,name:str,roll_no:int,marks:dict):
        self.name = name
        self.roll_no = roll_no
        self.marks = marks
class Branch:
    def __init__(self,students:list,name:str):
        if len(students) != 0 and not isinstance(students[0],Student):
            raise TypeError
        self.students = students
        self.name = name
class Year:
    def __init__(self,branches:list,year:int):
        if len(branches) != 0 and not isinstance(branches[0],Branch):
            raise TypeError
        self.year = year
        self.branches = branches
    def __repr__(self) -> str:
        return "Year "+str(self.year)

year2022Branch1Student1 = Student('N',1,{'Maths':100,"English":70})
year2022Branch1 = Branch([year2022Branch1Student1],'Branch 1')
year2022Branch2 = Branch([],'Branch 2')
year2022 = Year([year2022Branch1,year2022Branch1],2022)
D = []
for year in range(2023,2026):
    B = []
    for branch in range(1,3):
        b = Branch([],f'Branch {branch}')
        B.append(b)
    Y = Year(B,year)
    D.append(Y)
D # this is the overall database

[Year 2023, Year 2024, Year 2025]

#### 9) Using matplotlib plot the following functions on the domain: x = 0.5 to 100.0 in steps of 0.5.

$$
y = x \\
y = x^2 \\
y = \frac{x^3}{100} \\ 
y = \sin(x) \\
y = \frac{\sin(x)}{x} \\
y = \log(x) \\
y = e^x
$$

In [172]:
x = np.arange(0.5,100.5,0.5)
fL = {
    r"x":x,
    r"x^2":x**2,
    r"\frac{x^3}{100}":0.01*x**3,
    r"\sin(x)":np.sin(x),
    r"\frac{\sin(x)}{x}":np.sin(x)/x,
    r"\log(x)":np.log(x),
    r"e^x":np.exp(x),
}
fnames = list(fL.keys())
def update(i=(0,len(fnames)-1)):
    y = fL[fnames[i%len(fnames)]]
    plt.plot(x,y)
    plt.title('$ y = '+fnames[i]+'$')
    plt.xlabel('x')
    plt.ylabel('y')
    plt.xlim(0.5,100)
interact(update)

interactive(children=(IntSlider(value=3, description='i', max=6), Output()), _dom_classes=('widget-interact',)…

<function __main__.update(i=(0, 6))>

#### 10) Using numpy generate a matrix of size 20X5 containing random numbers drawn uniformly from the range of 1 to 2. Using Pandas create a dataframe out of this matrix. Name the columns of the dataframe as “a”, “b”, “c”, “d”, “e”. Find the column with the highest standard deviation. Find the row with the lowest mean.

##### Creating the dataframe

In [184]:
M = 1+np.random.random((20,5))
D = pd.DataFrame(M)
D.columns = ["a","b","c","d","e"]
D.head()

a         b         c         d         e
0  1.233081  1.319864  1.080084  1.766753  1.840640
1  1.746974  1.263662  1.285128  1.926436  1.189499
2  1.524891  1.583942  1.196542  1.132966  1.291286
3  1.036298  1.966514  1.121429  1.746969  1.668335
4  1.380449  1.987079  1.384848  1.762399  1.502413

##### Standard deviations of columns

In [185]:
D.std()

a    0.273625
b    0.310687
c    0.278837
d    0.253916
e    0.288970
dtype: float64

##### The column with highest standard deviation

In [188]:
print("Column with highest std. dev. is :",D.columns[(D.std()).argmax()])

Column with highest std. dev. is : b


##### Mean of a,b,c,d,e for all rows

In [190]:
D.mean(axis='columns').head()

0    1.448084
1    1.482340
2    1.345926
3    1.507909
4    1.603437
dtype: float64

##### row with minimum mean

In [192]:
print("The row with minimum mean has index ",D.mean(axis='columns').argmin())

The row with minimum mean has index  12


#### 11) Add a new column to the dataframe called “f” which is the sum of the columns “a”, “b”, “c”, “d”, “e”. Create another column called “g”. The value in the column “g” should be “LT8” if the value in the column “f” is less than 8 and “GT8” otherwise. Find the number of rows in the dataframe where the value in the column “g” is “LT8”. Find the standard deviation of the column “f” for the rows where the value in the column “g” is “LT8” and “GT8” respectively.

##### Adding column 'f'

In [194]:
D['f'] = D['a']+D['b']+D['c']+D['d']+D['e']
D.head()

a         b         c         d         e         f
0  1.233081  1.319864  1.080084  1.766753  1.840640  7.240422
1  1.746974  1.263662  1.285128  1.926436  1.189499  7.411700
2  1.524891  1.583942  1.196542  1.132966  1.291286  6.729628
3  1.036298  1.966514  1.121429  1.746969  1.668335  7.539545
4  1.380449  1.987079  1.384848  1.762399  1.502413  8.017187

##### Adding column 'g'

In [196]:
D['g'] = 'GT8'
D['g'].where(D['f']>8,'LT8',inplace=True)
D.head()

a         b         c         d         e         f    g
0  1.233081  1.319864  1.080084  1.766753  1.840640  7.240422  LT8
1  1.746974  1.263662  1.285128  1.926436  1.189499  7.411700  LT8
2  1.524891  1.583942  1.196542  1.132966  1.291286  6.729628  LT8
3  1.036298  1.966514  1.121429  1.746969  1.668335  7.539545  LT8
4  1.380449  1.987079  1.384848  1.762399  1.502413  8.017187  GT8

##### Number of rows with column g being 'LT8'

In [198]:
len(D[D['g']=='LT8'])

17

##### Standard deviation for column f for rows with g being LT8 and GT8

In [199]:
print("For rows with g=LT8 :",D['f'][(D['g']=='LT8')].std())
print("For rows with g=GT8 :",D['f'][(D['g']=='GT8')].std())

For rows with g=LT8 : 0.48517831192629
For rows with g=GT8 : 0.5164240583751355


#### 12) Write a small piece of code to explain broadcasting in numpy

Consider an array x with shape (5,1)

In [202]:
x = np.random.randint(0,10,(5,1))
x

array([[1],
       [2],
       [8],
       [2],
       [3]])

and an array y with shape (4)

In [203]:
y = np.random.randint(0,10,4)
y

array([3, 4, 0, 4])

To perform element wise multiplication of x and y, numpy broadcasts the arrays. Basically, numpy does the computation as if the arrays x and y were of shape (5,4). 

In [208]:
z = x*y
z

array([[ 3,  4,  0,  4],
       [ 6,  8,  0,  8],
       [24, 32,  0, 32],
       [ 6,  8,  0,  8],
       [ 9, 12,  0, 12]])


This output shape is obtained by 'stacking' the -1 axis of array x 4 times to match with size of -1 axis of y. 

Then, creating a new axis for y, making it of shape (1,4) and stacking the newly created -2 axis  5 times, so as to match with the size of axis 0 of x . 

In [214]:

print("x.shape:",list(x.shape))
print("y.shape:   ",list(y.shape))
print("----------------")
print("z.shape:",list(z.shape))

x.shape: [5, 1]
y.shape:    [4]
----------------
z.shape: [5, 4]


The matching of axis happens from the innermost axis to outermost axis. For example, if x had shape (7,2,8) and y had shape (7,2) , we will have a mismatch.

In [216]:
x = np.random.randint(0,10,(7,2,8))
y = np.random.randint(0,10,(7,2))
try:
    print(x*y)
except:
    print("mismatch")

mismatch


#### 13) Write a function to compute the argmin of a numpy array. The function should take a numpy array as input and return the index of the minimum element. You can use the np.argmin function to verify your solution.

Since we are talking about THE minimum index, I assume it's for the flattened array, just as is the default case for np.argmin

In [225]:
def ArgMin(L):
    if isinstance(L,np.ndarray):
        L = L.flatten()
    i = 0
    min_i = 0
    L = iter(L)
    min_val = next(L)
    for l in L:
        i+= 1
        if l < min_val:
            min_i = i
            min_val = l
    return min_i
correct = 0
incorrect = 0
for i in range(10):
    x = np.random.random((10,2))
    if ArgMin(x) == int(np.argmin(x)):
        correct += 1
    else:
        incorrect += 1
print("accuracy :",100*correct/(correct+incorrect))

accuracy : 100.0
